### ISSUE TITLE
Migrate plugins from/to `onPostBuild` and `onSuccess`

### ISSUE THREAD

**Issue by ehmicky** [netlify/plugins#134]
The full background of the discussion is [here](https://github.com/netlify/pod-the-builder/issues/45#issuecomment-681959870).

`onPostBuild` happens before deploy, and can prevent a build from being deployed.
`onSuccess` happens after deploy, and cannot prevent a build from being deployed.

We should send PRs to migrate plugins that either:
  - use `onPostBuild`, but the logic should happen after deploy
  - use `onEnd`, but errors should prevent a build from being deployed

After this is done, we should also send PRs to migrate plugins that use `utils.build.failBuild()` or `utils.build.cancelBuild()` within `onSuccess`, `onEnd` or `onError`.

**Comment by erezrokah** [comment]
Partial list of plugins:
- [ ] [lighthouse plugin](https://github.com/netlify-labs/netlify-plugin-lighthouse/blob/2705cbe10b2e389053e2408d1c3d6f2eed489192/src/index.js#L210)
- [ ] [is site vulnerable plugin](https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/blob/1e575415f44833ece58278bc8647da358f597af2/src/index.js#L6)

**Comment by ehmicky** [comment]
This is the list of plugins to review:
- onPostBuild
    - https://github.com/lukeocodes/netlify-plugin-algolia-index/blob/main/index.js
    - https://github.com/munter/netlify-plugin-checklinks/blob/master/lib/index.js
    - https://github.com/munter/netlify-plugin-subfont/blob/master/lib/index.js
    - https://github.com/munter/netlify-plugin-hashfiles/blob/master/lib/index.js
    - https://github.com/jlengstorf/netlify-plugin-visual-diff/blob/main/index.js
    - https://github.com/netlify-labs/netlify-plugin-sitemap/blob/master/index.js
    - https://github.com/sw-yx/netlify-plugin-no-more-404/blob/master/index.js
    - https://github.com/sw-yx/netlify-plugin-search-index/blob/master/index.js
    - https://github.com/netlify-labs/netlify-plugin-a11y/blob/master/plugin/index.js
    - https://github.com/cypress-io/netlify-plugin-cypress/blob/master/src/index.js
    - https://github.com/Tom-Bonnike/netlify-plugin-inline-source/blob/master/index.js
    - https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/blob/master/index.js
    - https://github.com/getsentry/sentry-netlify-build-plugin/blob/master/index.js
    - https://github.com/martinbean/netlify-plugin-amp-server-side-rendering/blob/master/src/index.js
    - https://github.com/chrisdwheatley/netlify-plugin-image-optim/blob/master/index.js
    - https://github.com/oliverroick/netlify-plugin-html-validate/blob/master/index.js
    - https://github.com/Brikl/opensource/blob/master/libs/netlify-plugin-next-dynamic/src/index.ts
    - https://github.com/ample/netlify-plugin-replace/blob/main/index.js
- onSuccess
    - https://github.com/tkadlec/netlify-build-plugin-speedcurve/blob/master/index.js
    - https://github.com/philhawksworth/netlify-plugin-minify-html/blob/master/index.js
    - https://github.com/AshikNesin/netlify-plugin-pushover/blob/master/index.js
    - https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/blob/master/src/index.js
    - https://github.com/borisschapira/netlify-build-plugin-dareboost/blob/master/index.js
    - https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/blob/master/index.js
    - https://github.com/netlify-labs/netlify-plugin-lighthouse/blob/master/src/index.js
    - https://github.com/perfbeacon/netlify-build-plugin-perfbeacon/blob/master/index.js
    - https://github.com/DebugBear/netlify-build-plugin-debugbear/blob/master/index.js
- onEnd
    - https://github.com/chrism2671/netlify-purge-cloudflare-on-deploy/blob/master/index.js
    - https://github.com/netlify-labs/netlify-plugin-debug-cache/blob/master/index.js
- onError
    - https://github.com/AshikNesin/netlify-plugin-pushover/blob/master/index.js

What to report:
  - `onPostBuild`: if the logic is meant to happen after deploy (`onSuccess` should be used instead then)
  - `onSuccess`/`onEnd`/`onError`: if errors within the event handler itself are meant to prevent the build from deploying (`onPostBuild` should be used instead then)
  - `onSuccess`/`onEnd`/`onError`: using `utils.build.failBuild()` or `utils.build.cancelBuild()` (`utils.build.failPlugin()` should be used instead)

**Comment by erezrokah** [comment]
| Plugin | Uses Events | Invokes `failBuild ` | Migration Needed | Migration Status | Assigned To |
|---|---|---|---|---|---|
|[netlify-build-plugin-speedcurve](https://github.com/tkadlec/netlify-build-plugin-speedcurve)|`onSuccess`| Yes | Switch to `failPlugin` |  Pending  | |
|[netlify-plugin-minify-html](https://github.com/philhawksworth/netlify-plugin-minify-html)|`onSuccess`| No | Switch to `onPostBuild ` |  Pending  | |
|[netlify-plugin-pushover](https://github.com/AshikNesin/netlify-plugin-pushover)|`onSuccess`| Yes | Switch to `failPlugin ` |  Pending  | |
|[netlify-plugin-is-website-vulnerable](https://github.com/erezrokah/netlify-plugin-is-website-vulnerable)|`onSuccess`| Yes | Switch to `onPostBuild ` |  [Done](https://github.com/netlify/plugins/pull/136)  | @erezrokah  |
|[netlify-build-plugin-dareboost](https://github.com/borisschapira/netlify-build-plugin-dareboost)|`onSuccess`| No | None |  Not Relevant  | |
|[netlify-plugin-submit-sitemap](https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap)|`onSuccess`| No | None |  Not Relevant  | |
|[netlify-plugin-lighthouse](https://github.com/netlify-labs/netlify-plugin-lighthouse)|`onSuccess`| Yes | Switch to `onPostBuild ` |  [Pending](https://github.com/netlify/plugins/pull/137)   | @erezrokah |
|[netlify-build-plugin-perfbeacon](https://github.com/PerfBeacon/netlify-build-plugin-perfbeacon)|`onSuccess`| Yes | Switch to `failPlugin ` |  Pending  | |
|[netlify-build-plugin-debugbear](https://github.com/DebugBear/netlify-build-plugin-debugbear)|`onSuccess`| No | None |  Not Relevant  | |
|[netlify-purge-cloudflare-on-deploy](https://github.com/chrism2671/netlify-purge-cloudflare-on-deploy)|`onEnd`| Yes | Switch to `failPlugin`, Use `onSuccess` instead of `onEnd` |  Pending  | |
|[netlify-plugin-debug-cache](https://github.com/netlify-labs/netlify-plugin-debug-cache)|`onEnd`| No | None |  Not Relevant  | |

**Comment by erezrokah** [comment]
@ehmicky, this is a partial table (missing `onPostBuild` plugins. Going to add them soon

**Comment by ehmicky** [comment]
We seem to only have 4 pending ones:
  - One plugin is from one of us, so we might be able to fix it.
  - The Pushover plugin is not a strong breaking change. The only change is: when the Pushover message fails to be sent, the build will not fail anymore.
  - The Sentry plugin should work as is, although the PR might improve its behavior.  
  - For the PerfBeacon plugin, when the performance test fails, the build will not fail anymore. However, it will still be notified in the deploy summary.

Overall, if we do fix the HTML minification plugin, it feels like we should be ready to move forward with breaking changes, without having to disable any of the three remaining plugins? What do you think?

**Comment by erezrokah** [comment]
I think PerfBeacon triggers a test and doesn't wait for it to complete:
https://github.com/PerfBeacon/netlify-build-plugin-perfbeacon/blob/84795d829048166c464d181fba0e2a359cc172c0/index.js#L42

so also not a strong breaking change like Pushover.

So pending the HTML minification one we're good to go

**Comment by ehmicky** [comment]
PR for the HTML minification plugin at https://github.com/netlify/plugins/pull/153

**Comment by ehmicky** [comment]
New plugins list is being deployed to production at https://github.com/netlify/buildbot/pull/968

**Comment by ehmicky** [comment]
There are only two plugins left: `netlify-build-plugin-perfbeacon` and `sentry-netlify-build-plugin`. 
The changes to those plugins are not critical, and we've migrated all other plugins, so I suggest we close this issue. @erezrokah What do you think?
