### ISSUE TITLE
Investigate how plugins are addressing deploy context

### ISSUE THREAD

**Issue by erezrokah** [netlify/plugins#139]
We have a bunch of plugins that are starting some kind of site audit (on the live site) in `onSuccess`.
Some of them only run in production context and some of them will also run on deploy previews (but audit the live site).

We need to look into how plugins are handling deploy context and also how  `URL, DEPLOY_URL, DEPLOY_PRIME_URL` envs are used.

Some plugins are assuming `onSuccess` happens after the site is live (which will be soon hopefully), which adds to the confusion.

Examples:
https://github.com/tkadlec/netlify-build-plugin-speedcurve/blob/0a54471574481fcca947fe356bab32ea190fae31/index.js#L18

https://github.com/PerfBeacon/netlify-build-plugin-perfbeacon/blob/84795d829048166c464d181fba0e2a359cc172c0/index.js#L20

https://github.com/borisschapira/netlify-build-plugin-dareboost/blob/1b191b9f3c887c9feec45ba6ea3cae84439e6394/index.js#L79

https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/blob/629df29da1a3c29528d31480abd00947735714fa/index.js#L67

https://github.com/DebugBear/netlify-build-plugin-debugbear/blob/c3855d63e471b12013694de6f8a8e85207e2e3e8/index.js#L45

**Comment by ehmicky** [comment]
The plugins using site URLs and assuming `onSuccess` is run after deploy are not a concern, since we are working on this feature as you mentioned.

I have just gone through all plugins:
  - `@algolia/netlify-plugin-crawler` uses [`DEPLOY_PRIME_URL`](https://github.com/algolia/algoliasearch-netlify/blob/9ef99f3a350fc3be56cf944c19e22a6459847119/plugin/src/index.ts#L58) to crawl the site after deploy, inside `onSuccess`.
  - `netlify-plugin-checklinks` uses [`URL`](https://github.com/munter/netlify-plugin-checklinks/blob/master/lib/index.js#L6) to resolve file paths to URLs shown to users in reports. Those reports are built in `onPostDeploy`. Since those reports mean the build and deploy should fail, so using the `URL` is fine.
  - `netlify-plugin-subfont` [does the same](https://github.com/Munter/netlify-plugin-subfont/blob/77ab808d53b6c22845f0c705806a34366689ee86/lib/index.js#L10) but to resolve font URLs. I think this might not work inside PRs and branches (which would use the production site instead), but I don't think this is a problem big enough for us to fix.
  - `netlify-plugin-hashfiles` [does something similar](https://github.com/Munter/netlify-plugin-hashfiles/blob/a1d6245669fb4b6837cc80cfeb4eb57d40a812d1/lib/index.js#L14)
  - `netlify-plugin-sitemap` uses [`URL`](https://github.com/netlify-labs/netlify-plugin-sitemap/blob/d5d9891e1e4fdea293de8336a160805aa965f8b9/index.js#L6) when creating the `sitemap.xml`. Since PRs and branches will not be crawled, I think this is fine.
  - `netlify-plugin-submit-sitemap` does something [similar](https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/blob/79266febf8fb9d43a8210eb4b21dd2e09cf15243/index.js#L5) but only runs if the `CONTEXT` is `production`, so that's ok.
  - `netlify-plugin-pushover` is using the [`URL`](https://github.com/AshikNesin/netlify-plugin-pushover/blob/70654a09c92e5ca029f7f31f3a024bc7811268ba/index.js#L2) in the message sent to Pushover. Again, this is not correct for PRs and branches, but I think this is ok enough.
  - `netlify-build-plugin-debugbear` is using the [`DEPLOY_URL`](https://github.com/DebugBear/netlify-build-plugin-debugbear/blob/186a9c30162ac9e443fc235546a77c301d9b6fec/index.js#L9) inside PRs, which is ok.
  - The following plugins need to make the build fail, so they are using an `onPostBuild` event and spawning a `localhost` server, which is good: `netlify-plugin-cypress`, [`netlify-plugin-is-website-vulnerable`](https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/blob/7a0412ed155cc0458e0a7539dac7788fbd859e24/src/index.js#L31), [`netlify-plugin-lighthouse`](https://github.com/netlify-labs/netlify-plugin-lighthouse/blob/0d1194fccbb46d2b57f0eaefadd82b9d752fbc09/src/index.js#L27).

So it seems everything is fine. Some plugins could probably use `CONTEXT === 'production' ? process.env.URL : process.env.DEPLOY_URL`, but I don't think we need to report this.

What do you think @erezrokah?

**Comment by erezrokah** [comment]
Thank you for doing this analysis, I think we can leave this to plugin authors to handle at the moment.
